blank_issues_enabled: true
contact_links:
  - name: Self-serve Request
    url: https://github.com/ipld/github-mgmt/edit/master/github/ipld.yml
    about: Propose a GitHub configuration change by modifying ipld.yml
